# Generated by Django 4.1 on 2022-08-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogId', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=200)),
                ('Author_Name', models.CharField(max_length=300)),
                ('start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
    ]
